CCIP-4703: Adding check for ChainFeeUpdates field
smartcontractkit/chainlink-ccip pull request #410
Opened 2024-12-31 15:55 UTC by b-gopalswami

Added missing check for ChainFeeUpdates field.

The review comment asks to check for non-positive value on DataAvailableFee field but I believe that can be zero when it is EVM chain so keeping that check for only non-negative values. Only if it is L2 chain, it should be non-positive.

2024-12-31 15:57 UTC, b-gopalswami commented on commit/chainfee/validate_observation.go
> +		if update.ChainFee.DataAvFeePriceUSD == nil || update.ChainFee.DataAvFeePriceUSD.Cmp(zero) < 0 {
I believe this DataAvFeePriceUSD might be zero for EVM chain and shouldn't be zero for L2 chains. Is that right? If at all we can know the given chain is L2, then we can add additional check here.

2025-01-06 14:30 UTC, makramkd commented on commit/chainfee/validate_observation.go
> +
Don't use errors.Wrap but fmt.Errorf

2025-01-06 14:30 UTC, makramkd commented on commit/chainfee/validate_observation.go
> +) error {
Can we have a unit test for this

2025-01-06 14:30 UTC, makramkd commented on commit/chainfee/validate_observation.go
> +) error {
And this

2025-01-06 14:30 UTC, makramkd commented on commit/chainfee/validate_observation.go
> +		return errors.Wrap(err, "failed to validate observed chains")
fmt.Errorf instead of errors.Wrap

2025-01-07 17:33 UTC, makramkd commented on commit/chainfee/validate_observation.go
> +func (p *processor) ValidateObservedChains(
This function shouldn't be public since it'll only get called from the chainfee processor

2025-01-08 08:35 UTC, asoliman92 commented on commit/chainfee/validate_observation.go
> +
We'll need to add extra checks here to make sure that all keys in all maps are exactly the same, otherwise we can end up with same lengths but for different chains on different maps.

2025-01-08 08:37 UTC, asoliman92 commented on commit/chainfee/validate_observation.go
Add validation for timpestamps making sure they're not zero or more than current utc timestamp.

2025-01-08 08:38 UTC, asoliman92 requested changes
Please add validation for timestamps and for keys in maps as mentioned in the comments.

2025-01-08 14:35 UTC, b-gopalswami commented on commit/chainfee/validate_observation.go
> +func (p *processor) ValidateObservedChains(
This is an interface method and can't be private.

2025-01-08 15:07 UTC, makramkd commented on commit/chainfee/validate_observation.go
> +func (p *processor) ValidateObservedChains(
Why is this an interface method?

2025-01-13 10:47 UTC, asoliman92 approved these changes
LGTM

2025-01-13 15:09 UTC, merged