bump go to 1.22.5
smartcontractkit/chainlink-ccip pull request #62
Opened 2024-08-13 13:57 UTC by makramkd

Bump Go to 1.22.5 to match whats in core.

2024-08-13 14:05 UTC, winder requested changes
Missed a 1.21 reference in one of the workflows

2024-08-13 15:08 UTC, winder approved these changes

2024-08-15 13:41 UTC, 0xnogo approved these changes

2024-08-19 16:49 UTC, winder commented on .github/workflows/ccip-ocr3-build-lint-test.yml
> +        go-version: ['1.22']
fix CI
```suggestion
        go-version: ['1.21', '1.22']
```

2024-08-19 16:59 UTC, merged